# Generated by Django 5.1.3 on 2025-04-01 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Banda",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                (
                    "foto",
                    models.ImageField(blank=True, null=True, upload_to="bandas/fotos/"),
                ),
                ("ano_formacao", models.IntegerField()),
                ("descricao", models.TextField(blank=True)),
                ("genero", models.CharField(max_length=50)),
                ("pais_origem", models.CharField(max_length=50)),
                ("website", models.URLField(blank=True)),
            ],
            options={
                "verbose_name": "Banda",
                "verbose_name_plural": "Bandas",
            },
        ),
        migrations.CreateModel(
            name="Album",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=100)),
                (
                    "capa",
                    models.ImageField(blank=True, null=True, upload_to="bandas/capas/"),
                ),
                ("ano_lancamento", models.IntegerField()),
                ("gravadora", models.CharField(blank=True, max_length=100)),
                ("descricao", models.TextField(blank=True)),
                (
                    "banda",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="albuns",
                        to="bandas.banda",
                    ),
                ),
            ],
            options={
                "verbose_name": "Álbum",
                "verbose_name_plural": "Álbuns",
            },
        ),
        migrations.CreateModel(
            name="Musica",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=100)),
                ("duracao", models.DurationField(blank=True, null=True)),
                ("ordem", models.IntegerField()),
                ("letra", models.TextField(blank=True)),
                ("link_spotify", models.URLField(blank=True)),
                ("link_youtube", models.URLField(blank=True)),
                (
                    "album",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="musicas",
                        to="bandas.album",
                    ),
                ),
            ],
            options={
                "verbose_name": "Música",
                "verbose_name_plural": "Músicas",
                "ordering": ["album", "ordem"],
            },
        ),
    ]
