# Generated by Django 5.1.3 on 2025-05-06 00:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="projeto",
            name="conceitos",
        ),
        migrations.RemoveField(
            model_name="projeto",
            name="desafios",
        ),
        migrations.RemoveField(
            model_name="imagem",
            name="projeto",
        ),
        migrations.RemoveField(
            model_name="perfil",
            name="user",
        ),
        migrations.RenameField(
            model_name="disciplina",
            old_name="link_moodle",
            new_name="moodle_url",
        ),
        migrations.RenameField(
            model_name="disciplina",
            old_name="link_pagina",
            new_name="pagina_uc",
        ),
        migrations.RenameField(
            model_name="projeto",
            old_name="demo_youtube",
            new_name="github",
        ),
        migrations.RemoveField(
            model_name="disciplina",
            name="docentes",
        ),
        migrations.RemoveField(
            model_name="projeto",
            name="repo_github",
        ),
        migrations.RemoveField(
            model_name="tecnologia",
            name="projetos",
        ),
        migrations.AddField(
            model_name="disciplina",
            name="docente",
            field=models.CharField(default="Desconhecido", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="projeto",
            name="conceito",
            field=models.TextField(default="Desconhecido"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="projeto",
            name="tecnologias",
            field=models.ManyToManyField(to="portfolio.tecnologia"),
        ),
        migrations.AddField(
            model_name="projeto",
            name="video_demo",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="tecnologia",
            name="repositorio",
            field=models.URLField(blank=True),
        ),
        migrations.CreateModel(
            name="Extras",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("info_adicional", models.TextField()),
                (
                    "projeto",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="portfolio.projeto",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ImagemProjeto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("imagem", models.ImageField(upload_to="projetos/")),
                (
                    "projeto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="imagens",
                        to="portfolio.projeto",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Conceito",
        ),
        migrations.DeleteModel(
            name="Desafio",
        ),
        migrations.AddField(
            model_name="projeto",
            name="desafios",
            field=models.TextField(default="Desconhecido"),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="Imagem",
        ),
        migrations.DeleteModel(
            name="Perfil",
        ),
    ]
