# Generated by Django 5.1.3 on 2025-05-20 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0002_remove_projeto_conceitos_remove_projeto_desafios_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Visitor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_key", models.CharField(max_length=40, unique=True)),
                ("first_visit", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
