# Generated by Django 5.1.3 on 2025-05-22 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0003_visitor"),
    ]

    operations = [
        migrations.CreateModel(
            name="AreaInteresse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("descricao", models.TextField()),
                ("disciplinas", models.ManyToManyField(to="portfolio.disciplina")),
                ("projetos", models.ManyToManyField(to="portfolio.projeto")),
                ("tecnologias", models.ManyToManyField(to="portfolio.tecnologia")),
            ],
        ),
    ]
