# Generated by Django 5.1.3 on 2025-04-01 16:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=50)),
                ("descricao", models.TextField(blank=True)),
                ("slug", models.SlugField(unique=True)),
            ],
            options={
                "verbose_name": "Categoria",
                "verbose_name_plural": "Categorias",
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=30)),
                ("slug", models.SlugField(unique=True)),
            ],
            options={
                "verbose_name": "Tag",
                "verbose_name_plural": "Tags",
            },
        ),
        migrations.CreateModel(
            name="Autor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("bio", models.TextField(blank=True)),
                (
                    "foto",
                    models.ImageField(
                        blank=True, null=True, upload_to="artigos/autores/"
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("website", models.URLField(blank=True)),
                ("twitter", models.URLField(blank=True)),
                ("github", models.URLField(blank=True)),
                ("linkedin", models.URLField(blank=True)),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Autor",
                "verbose_name_plural": "Autores",
            },
        ),
        migrations.CreateModel(
            name="Artigo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("subtitulo", models.CharField(blank=True, max_length=200)),
                ("slug", models.SlugField(unique=True)),
                ("conteudo", models.TextField()),
                (
                    "imagem_capa",
                    models.ImageField(
                        blank=True, null=True, upload_to="artigos/capas/"
                    ),
                ),
                ("data_criacao", models.DateTimeField(auto_now_add=True)),
                ("data_atualizacao", models.DateTimeField(auto_now=True)),
                ("data_publicacao", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("rascunho", "Rascunho"), ("publicado", "Publicado")],
                        default="rascunho",
                        max_length=10,
                    ),
                ),
                (
                    "tempo_leitura",
                    models.PositiveIntegerField(
                        default=5, help_text="Tempo estimado de leitura em minutos"
                    ),
                ),
                (
                    "destaque",
                    models.BooleanField(
                        default=False, help_text="Artigo em destaque na página inicial"
                    ),
                ),
                (
                    "fonte_original",
                    models.URLField(
                        blank=True,
                        help_text="URL da fonte original do artigo, se aplicável",
                    ),
                ),
                (
                    "autor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="artigos",
                        to="artigos.autor",
                    ),
                ),
                (
                    "categorias",
                    models.ManyToManyField(
                        related_name="artigos", to="artigos.categoria"
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True, related_name="artigos", to="artigos.tag"
                    ),
                ),
            ],
            options={
                "verbose_name": "Artigo",
                "verbose_name_plural": "Artigos",
                "ordering": ["-data_publicacao", "-data_criacao"],
            },
        ),
        migrations.CreateModel(
            name="Comentario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("website", models.URLField(blank=True)),
                ("conteudo", models.TextField()),
                ("data_criacao", models.DateTimeField(auto_now_add=True)),
                ("aprovado", models.BooleanField(default=False)),
                (
                    "artigo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comentarios",
                        to="artigos.artigo",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="respostas",
                        to="artigos.comentario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Comentário",
                "verbose_name_plural": "Comentários",
                "ordering": ["data_criacao"],
            },
        ),
        migrations.CreateModel(
            name="Avaliacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                (
                    "pontuacao",
                    models.IntegerField(
                        choices=[
                            (1, "1 - Fraco"),
                            (2, "2 - Regular"),
                            (3, "3 - Bom"),
                            (4, "4 - Muito Bom"),
                            (5, "5 - Excelente"),
                        ]
                    ),
                ),
                ("comentario", models.TextField(blank=True)),
                ("data_criacao", models.DateTimeField(auto_now_add=True)),
                (
                    "artigo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="avaliacoes",
                        to="artigos.artigo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Avaliação",
                "verbose_name_plural": "Avaliações",
                "unique_together": {("artigo", "email")},
            },
        ),
    ]
