# Generated by Django 5.2.1 on 2025-05-21 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("artigos", "0002_avaliacao_usuario_comentario_usuario"),
    ]

    operations = [
        migrations.AlterField(
            model_name="avaliacao",
            name="comentario",
            field=models.TextField(
                blank=True, help_text="Comentário opcional sobre sua avaliação"
            ),
        ),
        migrations.AlterField(
            model_name="avaliacao",
            name="pontuacao",
            field=models.IntegerField(
                choices=[
                    (1, "1 - Fraco"),
                    (2, "2 - Regular"),
                    (3, "3 - Bom"),
                    (4, "4 - Muito Bom"),
                    (5, "5 - Excelente"),
                ],
                help_text="Avalie de 1 a 5 estrelas",
            ),
        ),
        migrations.AlterField(
            model_name="comentario",
            name="conteudo",
            field=models.TextField(
                help_text="Apenas texto é permitido nos comentários."
            ),
        ),
    ]
