# Generated by Django 5.2.1 on 2025-05-21 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "artigos",
            "0003_alter_avaliacao_comentario_alter_avaliacao_pontuacao_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="avaliacao",
            name="comentario",
            field=models.TextField(
                blank=True, help_text="Não utilizado conforme requisito"
            ),
        ),
        migrations.AlterField(
            model_name="avaliacao",
            name="email",
            field=models.EmailField(
                help_text="Preenchido automaticamente do usuário", max_length=254
            ),
        ),
        migrations.AlterField(
            model_name="avaliacao",
            name="nome",
            field=models.CharField(
                help_text="Preenchido automaticamente do usuário", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="comentario",
            name="email",
            field=models.EmailField(
                help_text="Preenchido automaticamente do usuário", max_length=254
            ),
        ),
        migrations.AlterField(
            model_name="comentario",
            name="nome",
            field=models.CharField(
                help_text="Preenchido automaticamente do usuário", max_length=100
            ),
        ),
    ]
